# Generated by Django 4.2.6 on 2023-10-19 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("CavQuest_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("approved_status", models.BooleanField(default=False)),
                ("hint", models.ManyToManyField(to="CavQuest_app.hint")),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CavQuest_app.place",
                    ),
                ),
                (
                    "task_name",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CavQuest_app.task",
                    ),
                ),
            ],
        ),
    ]
