# Generated by Django 4.2.6 on 2023-10-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CavQuest_app", "0003_task_approved_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usersubmission",
            old_name="approved_status",
            new_name="approved",
        ),
        migrations.RemoveField(
            model_name="usersubmission",
            name="hint",
        ),
        migrations.RemoveField(
            model_name="usersubmission",
            name="place",
        ),
        migrations.RemoveField(
            model_name="usersubmission",
            name="task_name",
        ),
        migrations.AddField(
            model_name="usersubmission",
            name="hint1",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="usersubmission",
            name="hint2",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="usersubmission",
            name="hint3",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="usersubmission",
            name="place_text",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="usersubmission",
            name="state_text",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="usersubmission",
            name="task_text",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
