# Generated by Django 4.2.6 on 2023-10-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CavQuest_app', '0004_rename_approved_status_usersubmission_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=10),
        ),
    ]
