# Generated by Django 4.2.5 on 2023-11-01 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("CavQuest_app", "0005_usersubmission_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubmission",
            name="difficulties",
            field=models.CharField(
                choices=[("easy", "EASY"), ("medium", "MEDIUM"), ("hard", "HARD")],
                default="easy",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="Difficulty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place_text", models.CharField(max_length=500)),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CavQuest_app.task",
                    ),
                ),
            ],
        ),
    ]
