# Generated by Django 4.2.7 on 2023-11-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CavQuest_app", "0007_remove_place_state_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="latitude",
            field=models.FloatField(default=False),
        ),
        migrations.AddField(
            model_name="place",
            name="longitude",
            field=models.FloatField(default=False),
        ),
        migrations.AddField(
            model_name="usersubmission",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usersubmission",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
