# Generated by Django 4.2.7 on 2023-11-11 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CavQuest_app", "0013_place_facts_place_image_usersubmission_facts_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="facts",
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name="usersubmission",
            name="facts",
            field=models.TextField(max_length=100000, null=True),
        ),
    ]
