# Generated by Django 4.2.7 on 2023-11-11 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CavQuest_app", "0014_alter_place_facts_alter_usersubmission_facts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="image",
            field=models.ImageField(null=True, upload_to="staticfiles/location_images"),
        ),
        migrations.AlterField(
            model_name="usersubmission",
            name="image",
            field=models.ImageField(null=True, upload_to="staticfiles/location_images"),
        ),
    ]
