# Generated by Django 4.2.7 on 2023-11-11 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CavQuest_app", "0015_alter_place_image_alter_usersubmission_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersubmission",
            name="facts",
        ),
        migrations.RemoveField(
            model_name="usersubmission",
            name="image",
        ),
    ]
