# Generated by Django 4.2.7 on 2023-11-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CavQuest_app", "0016_remove_usersubmission_facts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="difficulty",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "EASY"), ("medium", "MEDIUM"), ("hard", "HARD")],
                default="easy",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="difficulty",
            name="description",
            field=models.CharField(max_length=10),
        ),
    ]
