# Generated by Django 4.2.5 on 2023-11-12 00:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("CavQuest_app", "0019_alter_userprofile_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="completed_by",
            field=models.ManyToManyField(
                related_name="completed_tasks", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
