# Generated by Django 4.2 on 2023-11-12 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CavQuest_app", "0022_adminsubmission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminsubmission",
            name="facts",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="adminsubmission",
            name="latitude",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="adminsubmission",
            name="longitude",
            field=models.FloatField(null=True),
        ),
    ]
