# Generated by Django 4.2 on 2023-11-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CavQuest_app", "0024_alter_place_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminsubmission",
            name="facts",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="place",
            name="image",
            field=models.ImageField(null=True, upload_to="location_pictures/"),
        ),
    ]
