# Generated by Django 4.2 on 2023-11-12 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CavQuest_app", "0022_task_image_alter_place_image"),
        ("CavQuest_app", "0026_alter_adminsubmission_image"),
    ]

    operations = []
